name: Addy Foundation Website

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main # Replace 'main' with your branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest # The operating system for the workflow

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to Hostinger via FTP
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@4.5.0
        with:
          server: ${{ secrets.FTP_HOST }}       # Hostinger FTP server (e.g., ftp.example.com)
          username: ${{ secrets.FTP_USERNAME }} # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }} # Your FTP password
          local-dir: ./                         # The directory containing your HTML files
          server-dir: /public_html/             # Hostinger's public root directory
